@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJieiIsImlhdCI6MTY3NjQ3NTkzNywiZXhwIjoxNjc2NDc3Mzc3fQ.l3qcCXWYjo-T2Mxcbeibvuu21dp4olVrgGbTwPCMvPM
POST {{url}}/user/register
Content-Type: application/json

{
    "username": "bz",
    "password": "asdf",
    "email": "asdf@asdf.com"
}

###

GET {{url}}/demo/auth/hello
Authorization: Bearer {{token}}